### ISSUE TITLE
upload an image in the jiva use case

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeDialogManager#26]
the png file needs to be in a particular format otherwise the AI model returns an error.
Error shown in the dialog manager (which is good).
can you change the format ? 
image location  : https://drive.google.com/drive/folders/1nCOPD0hD3hp_WKoQWVHHt6bly0lcwIIC
![image](https://github.com/isee4xai/iSeeDialogManager/assets/91963804/992633eb-18cb-42d9-ba36-ca7b871e27d3)

**Comment by anjanaw** [comment]
Sorted. Use images in the Google Drive folder.
