### ISSUE TITLE
Model does not execute in use case setup

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/iSeeDialogManager#33]
The model does not seem to execute correctly when defining a use case.  

I have the following error message when I click on "Validate Model Prediction"

![image](https://github.com/isee4xai/iSeeDialogManager/assets/92316278/410f448f-2b53-44c9-bc66-fa8c6ca39f86)

use case id: 645e3b81cbf032384d5a550e

Thank you !

**Comment by anjanaw** [comment]
@bfleisch  Attached is the log from portainer models_sk-1. Has anything changed in this model recently? It is complaining about a missing "stemmer_tokenizer"
<img width="846" alt="Screenshot 2024-02-06 at 13 17 16" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/63f8900a-e492-44cc-ad2b-8b1fddb0db08">

**Comment by anjanaw** [comment]
<img width="952" alt="Screenshot 2024-02-14 at 12 07 05" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/a0d352f7-7e83-4c1a-a531-cd0a0c0bb139">
issue still exists @bfleisch

**Comment by bfleisch** [comment]
hi @anjanaw  - thanks a lot. I've fixed the bug and uploaded the model.

I'm now able to move one step further, but I'm now stuck at this stage:

![image](https://github.com/isee4xai/iSeeDialogManager/assets/92316278/ec1f2d22-34d0-4f08-b089-8866e607bc98)


The chatbot is disconnected. 

I have not seen any specific error message in the log files (modelhub, sklearn model, dialog manager)...

thanks!
Bruno

**Comment by anjanaw** [comment]
Dialogue Manager did not receive an explanation from Text/LIME

<img width="951" alt="Screenshot 2024-02-14 at 15 17 49" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/399ea428-2a17-4892-94ce-d1a3abee3658">

and yes there are no logs here. but Jesus is working on improving these. 
<img width="951" alt="Screenshot 2024-02-14 at 15 17 35" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/2c9e6cd8-029d-4bbb-a03a-e92580640865">

Please contact Jesus to investigate the issue. Would be easier if you can close this and move the issue to issueTracker so we can tag Jesus.
