### ISSUE TITLE
"chatbot is now disconnected" error message

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/iSeeDialogManager#34]
I have the following error message when executing the chabot  for use case 645e3b81cbf032384d5a550e

Maybe this is related to issue #33 ?

![image](https://github.com/isee4xai/iSeeDialogManager/assets/92316278/934e83b3-b3b8-47c7-ba00-423edaa2d5e5)

thank you !

**Comment by anjanaw** [comment]
Please see #28
